import{a as l,S as d,N as p,K as f,P as w}from"./assets/vendor-fa5600b1.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function i(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=i(t);fetch(t.href,r)}})();l.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function y(){return(await l.get("/reviews")).data}const u=document.querySelector(".reviews-list");function m(e,s,i,a){return`
     <li class="reviews-list-items swiper-slide" data-id="${e}">
     <img class="reviews-image" src="${i}" alt="" 
            width="48"
            height="48"
            loading="lazy" />
          <div class="reviews-text-content">
            <h3 class="reviews-name-header">${s}</h3>
            <p class="reviews-main-text">${a}</p>
          </div>
        </li>
  `}function v(){const e='<p class="end-message">Not found</p>';u.insertAdjacentHTML("afterend",e)}function b(e){return e.map(({_id:s,author:i,avatar_url:a,review:t})=>m(s,i,a,t)).join("")}function h(e){const s=b(e);u.insertAdjacentHTML("beforeend",s)}const g=document.querySelector(".swiper"),o=document.querySelector(".button-next"),n=document.querySelector(".button-prev"),O=new d(g,{modules:[p,f,w],navigation:{nextEl:o,prevEl:n},direction:"horizontal",autoHeight:!1,autoWidth:!1,watchOverflow:!0,keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},breakpoints:{320:{slidesPerView:"auto",spaceBetween:22},767:{slidesPerView:2,spaceBetween:16},1280:{slidesPerView:3,spaceBetween:42},1440:{slidesPerView:4,spaceBetween:16}}});O.update();async function N(){try{const e=await y();e.length===0?v():h(e)}catch(e){console.error("Error fetching reviews:",e)}}const L=new MutationObserver(e=>{e.forEach(s=>{s.attributeName==="class"&&(o.classList.contains("swiper-button-disabled")?(o.style.opacity="0.5",o.style.cursor="not-allowed"):(o.style.opacity="1",o.style.cursor="pointer"))})});L.observe(o,{attributes:!0});const P=new MutationObserver(e=>{e.forEach(s=>{s.attributeName==="class"&&(n.classList.contains("swiper-button-disabled")?(n.style.opacity="0.5",n.style.cursor="not-allowed"):(n.style.opacity="1",n.style.cursor="pointer"))})});P.observe(n,{attributes:!0});N();
//# sourceMappingURL=commonHelpers.js.map
