import{a as d,S as p,N as f,K as w,P as v}from"./assets/vendor-cef296b0.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))a(s);new MutationObserver(s=>{for(const i of s)if(i.type==="childList")for(const c of i.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function r(s){const i={};return s.integrity&&(i.integrity=s.integrity),s.referrerPolicy&&(i.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?i.credentials="include":s.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function a(s){if(s.ep)return;s.ep=!0;const i=r(s);fetch(s.href,i)}})();d.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function y(){return(await d.get("/reviews")).data}const u=document.querySelector(".reviews-list");function m(e,t,r,a){return`
     <li class="reviews-list-items swiper-slide" data-id="${e}">
     <img class="reviews-image" src="${r}" alt="" 
            width="48"
            height="48"
            loading="lazy" />
          <div class="reviews-text-content">
            <h3 class="reviews-name-header">${t}</h3>
            <p class="reviews-main-text">${a}</p>
          </div>
        </li>
  `}function b(){const e='<p class="end-message">Not found</p>';u.insertAdjacentHTML("afterend",e)}function h(e){return e.map(({_id:t,author:r,avatar_url:a,review:s})=>m(t,r,a,s)).join("")}function g(e){const t=h(e);u.insertAdjacentHTML("beforeend",t)}const L=document.querySelector(".swiper"),o=document.querySelector(".button-next"),n=document.querySelector(".button-prev"),O=new p(L,{modules:[f,w,v],navigation:{nextEl:o,prevEl:n},direction:"horizontal",autoHeight:!1,autoWidth:!1,watchOverflow:!0,keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},breakpoints:{320:{slidesPerView:"auto",spaceBetween:22},767:{slidesPerView:2,spaceBetween:16},1280:{slidesPerView:3,spaceBetween:42},1440:{slidesPerView:4,spaceBetween:16}}});O.update();async function E(){try{const e=await y();e.length===0?b():g(e)}catch(e){console.error("Error fetching reviews:",e)}}const N=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(o.classList.contains("swiper-button-disabled")?(o.style.opacity="0.5",o.style.cursor="not-allowed"):(o.style.opacity="1",o.style.cursor="pointer"))})});N.observe(o,{attributes:!0});const P=new MutationObserver(e=>{e.forEach(t=>{t.attributeName==="class"&&(n.classList.contains("swiper-button-disabled")?(n.style.opacity="0.5",n.style.cursor="not-allowed"):(n.style.opacity="1",n.style.cursor="pointer"))})});P.observe(n,{attributes:!0});E();const l=document.querySelectorAll(".accordion-title"),x=document.querySelectorAll(".accordion-content");l.forEach(e=>e.addEventListener("click",()=>{const t=document.querySelector("#"+e.dataset.tab);t.classList.contains("active")?(t.classList.remove("active"),t.style.maxHeight=0):(x.forEach(r=>{r.classList.remove("active"),r.style.maxHeight=0}),l.forEach(r=>r.classList.remove("active")),e.classList.add("active"),t.classList.add("active"),t.style.maxHeight=t.scrollHeight+"px")}));
//# sourceMappingURL=commonHelpers.js.map
